---
title: "Example"
author: "David"
output: html_document
---

```{r,  include =FALSE}
knitr::opts_chunk$set(echo=TRUE)
BASE <- database()
selected_var_name <- input$selected_var
selected_var_pos <- base::match(selected_var_name, colnames(BASE))

sentence_VR <- "VR <- BASE[,selected_var_pos] 
                VR"

sentence_VR <- gsub(pattern = "selected_var_pos", 
                    replacement = selected_var_pos, 
                    x = sentence_VR)

```


## Esto es TExto

Lalala
```{r, include =T}
plot(BASE)
```


```{r, include =T}
# Aislamos el peso de los alumnos en un nuevo objeto
# llamado "VR".
parse(text = sentence_VR)
eval(parse(text = sentence_VR))
print(sentence_VR)
print(parse(text = sentence_VR))
#VR <- BASE[,selected_var_pos]
#VR
cat(sentence_VR)
#cat(parse(text = sentence_VR))

```
<br>
<br>

```{r, include =T}
# Media
mean(VR)
```
<br>
<br>

```{r, include =T}
# Mediana 
median(VR)
```
<br>
<br>

```{r, include =T}
# Minimo
min(VR)
```
<br>
<br>

```{r, include =T}
# Maximo
max(VR)
```
<br>
<br>

```{r, include =T}
# Cantidad de Datos
length(VR)
```
<br>
<br>

```{r, include =T}
# Varianza
var(VR)
```
<br>
<br>

```{r, include =T}
# Desvio Estandard
sd(VR)
```
<br>
<br>

```{r, include =T}
# Summary
summary(VR)
```
<br>
<br>

```{r, include =T}
# Objeto MEDIDAS
MEDIDAS <- summary(VR)
MEDIDAS
```
<br>
<br>

```{r, include =T}
# Solo algunas MEDIDAS
MEDIDAS[c(2,3,5)]
```
<br>
<br>



